# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Dev environment
variables:
  # Global
  ap_vm_image: ubuntu-20.04

  namespace: mlopsTmpl #Note: A namespace with many characters will cause storage account creation to fail due to storage account names having a limit of 24 characters.
  postfix: 0001
  location: eastus
  environment: dev
  enable_aml_computecluster: true
  enable_monitoring: false

  ownerTag: mlopsTmpl
  projectTag: mlopsTmpl

  # Azure DevOps - Service Connection
  ado_service_connection_rg: mlopsTmpl-ado-rg-servConn-dev
  ado_service_connection_aml_ws: mlopsTmpl-ado-amlWs-servConn-dev

  # DO NOT TOUCH

  # For pipeline reference
  resourceMap:
    resource_group: $(namespace)-$(postfix)-$(environment)-rg
    aml_workspace: $(namespace)-$(postfix)-$(environment)-amlw
    application_insights: $(namespace)-$(postfix)$(environment)-appi
    key_vault: $(namespace)-$(postfix)-$(environment)-kv
    container_registry: $(namespace)-$(postfix)-$(environment)-cr
    storage_account: $(namespace)-$(postfix)-$(environment)-sa

  # For terraform reference
  terraform_version: 1.3.6
  terraform_workingdir: infrastructure
  terraform_st_location: $(location)
  terraform_st_resource_group: rg-$(namespace)-$(postfix)$(environment)-tf
  terraform_st_storage_account: st$(namespace)$(postfix)$(environment)tf
  terraform_st_container_name: default
  terraform_st_key: mlops-tab